#include "pomo_model.h"

// =========================================================
// GLOBAL SESSION STATE
// =========================================================
// This holds the actual data in RAM during a timer session.
// When the timer hits 0, this struct will be passed to your 
// SD card logic (and eventually Notion sync).

pomoTimer_t active_session = {
    .timerID = "session_001",  // Will be generated by RTC later
    .focusDuration = 25,
    .pomoCount = 0.0,
    .classTag = "Coding",      // Default tag
    .dateAndTime = "12:00",    // Will be pulled from DS3231 later
    .isCompleted = false,
    .timerState = pomoTimer_IDLE
};